# Excluded files
exclude:
- README.md
- LICENSE
- CNAME

# Gems
gems:
- jekyll-github-metadata
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jemoji

repository: "srbala/srbala.github.io"

jekyll-mentions: https://twitter.com

# SCSS
sass:
  style: :compressed
  
# Site info
url: https://srbala.github.io
title: "Bala's Open Source Stuff"
name: "Bala Raman"
description: "Experiments, tools and other projects"
logo: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c?s=300"

twitter:
  username: srbala

author:
  twitter: srbala
  
seo:
  author: "Bala Raman"
